name: Deploy to Digital Ocean

on:
  release:
    types: [created]
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
    - name: Deploy new STABLE release
      run: |
        echo "deploying from master branch"
        cd ~/highlanderbot-release
        sudo systemctl stop highlanderbot-release.service
        git fetch
        git checkout master
        git merge origin/master
        npm install
        sudo systemctl start highlanderbot-release.service
        echo "done"
        echo "deploying from devel branch"
        cd ~/highlanderbot-devel
        sudo systemctl stop highlanderbot-devel.service
        git fetch
        git checkout devel
        git merge origin/devel
        npm install
        sudo systemctl start highlanderbot-devel.service
        echo "done"
